### ISSUE TITLE
[Bug]: Installing Fundus on macOS Ventura

### ISSUE THREAD

**Issue by dobbersc** [flairNLP/fundus#284]
### Describe the bug

Trying to install Fundus on macOS Ventura with pip from master fails.

### How to reproduce

```python
git clone https://github.com/flairNLP/fundus.git
cd fundus
pip install -e .
```
```


### Expected behavior.

Fundus should install without any problems on MacOS.

### Logs and Stack traces

```stacktrace
Obtaining file:///Users/a2/projects/fundus
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Collecting dill~=0.3.5.1 (from fundus==0.0.1)
  Using cached dill-0.3.5.1-py2.py3-none-any.whl (95 kB)
Collecting FastWARC~=0.12.2 (from fundus==0.0.1)
  Using cached FastWARC-0.12.2.tar.gz (355 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "/Users/a2/miniforge3/envs/fundus/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/a2/miniforge3/envs/fundus/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/a2/miniforge3/envs/fundus/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/jb/ygsf054d2v910211h28f2bhw0000gn/T/pip-build-env-et9i4_ce/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/jb/ygsf054d2v910211h28f2bhw0000gn/T/pip-build-env-et9i4_ce/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 121, in <module>
        File "/private/var/folders/jb/ygsf054d2v910211h28f2bhw0000gn/T/pip-build-env-et9i4_ce/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/jb/ygsf054d2v910211h28f2bhw0000gn/T/pip-build-env-et9i4_ce/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/private/var/folders/jb/ygsf054d2v910211h28f2bhw0000gn/T/pip-build-env-et9i4_ce/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 898, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/private/var/folders/jb/ygsf054d2v910211h28f2bhw0000gn/T/pip-build-env-et9i4_ce/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/private/var/folders/jb/ygsf054d2v910211h28f2bhw0000gn/T/pip-build-env-et9i4_ce/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 128, in read_configuration
          validate(subset, filepath)
        File "/private/var/folders/jb/ygsf054d2v910211h28f2bhw0000gn/T/pip-build-env-et9i4_ce/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 55, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project`.
      configuration error: `project` must contain ['name'] properties
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
```


### Screenshots

_No response_

### Additional Context

The report log and run itself are from @aynetdia.

### Environment

```markdown
OS: macOS Ventura 13.1
Fundus Version: master
Python Version: 3.9.16
```

**Comment by MaxDall** [comment]
I tried to reproduce the bug but couldn't manage to do so. I tried 

- locally using Windows 11 and different versions of setuptool
- through the CI using a test matrix with [ubunto-latest, macos-latest (12), windows-latest] x  [3.8, 3.9, 3.10, 3.11]

@aynetdia could you provide some info about the package versions you are using? Especially `setuptools` and `wheel` .

**Comment by aynetdia** [comment]
I apologize for the late reply, haven't seen the notification.

I still get the same bug on macOS Ventura 13.4.1, here are the package specifications:

```
Package    Version
---------- -------
pip        23.2.1
setuptools 68.0.0
wheel      0.41.0
```
