### ISSUE TITLE
[Bug]: New process could not start before the current process has finished its bootstrapping phase

### ISSUE THREAD

**Issue by datitran** [flairNLP/fundus#568]
### Describe the bug

I get a weird bug when I use `*PublisherCollection`. For any `max_articles` even if the number is 2, I get a new process ... error and I also get this problem when processes is not set to 1 when specifying a `PublisherCollection.*`.

### How to reproduce

```python
from fundus import PublisherCollection, CCNewsCrawler

# initialize the crawler using all publishers supported by fundus
crawler = CCNewsCrawler(*PublisherCollection, processes=1)

# crawl 1 million articles and print
for article in crawler.crawl(max_articles=1000000):
  print(article)
```

### Expected behavior.

Return the news article in the terminal

### Logs and Stack traces

```stacktrace
(newscrawl)  ✘ ✝  ~/Desktop/crawl  python main.py
Traceback (most recent call last):
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/site-packages/fundus/scraping/crawler.py", line 90, in get_proxy_tqdm
    manager.start()
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/datitran/Desktop/crawl/main.py", line 7, in <module>
    for article in crawler.crawl(max_articles=1000000):
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/site-packages/fundus/scraping/crawler.py", line 296, in crawl
    for article in self._build_article_iterator(
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/site-packages/fundus/scraping/crawler.py", line 618, in _build_article_iterator
    with get_proxy_tqdm(total=len(warc_paths), desc="Process WARC files", disable=self.disable_tqdm) as bar:
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/site-packages/fundus/scraping/crawler.py", line 93, in get_proxy_tqdm
    manager.shutdown()
AttributeError: 'TQDMManager' object has no attribute 'shutdown'
Traceback (most recent call last):
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/site-packages/fundus/scraping/crawler.py", line 90, in get_proxy_tqdm
    manager.start()
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    for article in crawler.crawl(max_articles=1000000):
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/site-packages/fundus/scraping/crawler.py", line 296, in crawl
    for article in self._build_article_iterator(
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/site-packages/fundus/scraping/crawler.py", line 618, in _build_article_iterator
    with get_proxy_tqdm(total=len(warc_paths), desc="Process WARC files", disable=self.disable_tqdm) as bar:
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/datitran/miniconda3/envs/newscrawl/lib/python3.8/site-packages/fundus/scraping/crawler.py", line 93, in get_proxy_tqdm
    manager.shutdown()
AttributeError: 'TQDMManager' object has no attribute 'shutdown'
```

### Environment

```markdown
OS: Mac Sonoma 14.3

Brotli==1.1.0
certifi==2024.7.4
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
cssselect==1.2.0
dill==0.3.8
FastWARC==0.14.7
feedparser==6.0.11
fundus==0.4.0
idna==3.7
langdetect==1.0.9
lxml==4.9.4
more-itertools==9.1.0
powerline-status==2.7
python-dateutil==2.9.0.post0
requests==2.32.3
sgmllib3k==1.0.0
six==1.16.0
tqdm==4.66.4
typing_extensions==4.12.2
urllib3==2.2.2
validators==0.33.0
```

**Comment by MaxDall** [comment]
Hi @datitran, sorry to hear that you are having problems using Fundus.

This looks like an error caused by the [start method](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) used by your system to start a new process. If your OS utilizes `spawn` as a start method, you must wrap your code within a `__name__ == "__main__"` block to prevent Python from executing your code in each process. That's just one of the caveats coming with the multiprocessing implementation of Python. Here is a good Stackoverflow [post](https://stackoverflow.com/questions/20360686/compulsory-usage-of-if-name-main-in-windows-while-using-multiprocessi) for some more insights.

What keeps me wondering is that `spawn` is normally used for Windows-based systems whereas you're executing your code on Mac OS.

Just to be sure, could you run this little code snippet and confirm that it outputs the string `spawn`?

```python
import multiprocessing

print(multiprocessing.get_start_method())
```

If so, the solution to your problem would be to wrap your code as follows:

```python
from fundus import PublisherCollection, CCNewsCrawler

if __name__ == '__main__':
    # initialize the crawler using all publishers supported by fundus
    crawler = CCNewsCrawler(*PublisherCollection, processes=1)

    # crawl 1 million articles and print
    for article in crawler.crawl(max_articles=1000000):
        print(article)
```

Further, if you want to omit multiprocessing entirely, the correct value for the `processes` parameter would be `0`

Please let me know if that solves your problem :)

**Comment by datitran** [comment]
Cool yeh this works. Funny enough when I debugged it ChatGPT was already telling me to wrap it around the main entrypoint 😅
