### ISSUE TITLE
[Bug]: in detach return _winapi.DuplicateHandle( PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by Hussnain178** [flairNLP/fundus#571]
### Describe the bug

this is returning when ever I run this basic script

### How to reproduce

```python
from fundus import CCNewsCrawler, PublisherCollection

if __name__ == "__main__":
    crawler = CCNewsCrawler(*PublisherCollection)
    dt = []
    for article in crawler.crawl(max_articles=10):
        print(article)
        dt.append(article)

    h = 1
```

### Expected behavior.

don't know

### Logs and Stack traces

```stacktrace
CCNewsCrawler will automatically use all available cores: 12. For optimal performance, we recommend manually setting the number of processes using the <processes> parameter. A good rule of thumb is to allocate `one process per 200 Mbps of bandwidth`.
Process WARC files:   0%|          | 0/39950 [00:00<?, ?it/s]Exception ignored in tp_clear of: <class 'memoryview'>
Traceback (most recent call last):
  File "C:\Users\Hussnain\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1487, in enumerate
    return list(_active.values()) + list(_limbo.values())
BufferError: memoryview has 1 exported buffer
Traceback (most recent call last):
  File "C:\Users\Hussnain\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\Hussnain\AppData\Local\Programs\Python\Python310\lib\multiprocessing\connection.py", line 962, in rebuild_pipe_connection
    handle = dh.detach()
  File "C:\Users\Hussnain\AppData\Local\Programs\Python\Python310\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\Hussnain\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\Hussnain\AppData\Local\Programs\Python\Python310\lib\multiprocessing\connection.py", line 962, in rebuild_pipe_connection
    handle = dh.detach()
  File "C:\Users\Hussnain\AppData\Local\Programs\Python\Python310\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Access is denied
python-BaseException
python-BaseException
Traceback (most recent call last):
  File "C:\Users\Hussnain\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\Hussnain\AppData\Local\Programs\Python\Python310\lib\multiprocessing\connection.py", line 962, in rebuild_pipe_connection
    handle = dh.detach()
  File "C:\Users\Hussnain\AppData\Local\Programs\Python\Python310\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Access is denied
python-BaseException
```

### Environment

```markdown
python 3.10
```

**Comment by addie9800** [comment]
Hi @Hussnain178 ,
I am sorry to hear you are having trouble with fundus. Unfortunately, I was unable to reproduce the error on Python3.10 with my Windows machine using a fresh installation of fundus. Judging by the traceback of the error the issue seems to be within an external package and not directly in fundus. Could you run `python -m pip freeze` and give us the results?

**Comment by MaxDall** [comment]
Thanks @addie9800 

@Hussnain178 Could you try running your code as admin?
